// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 07 Mar 2018 17:31:54 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package mupdf provides Go bindings for MuPDF, a lightweight PDF, XPS, and E-book viewer library.
*/
package mupdf
